# -*- coding: utf-8 -*-
"""Knapsack problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kXbdW6l87LAKihQsIU1g_IkGKAHkkjm
"""

# Loads a filename to create knapsack problem instance.
# The function returns a tuple, where the first element represents W and,
# the second, a list of the items within the instance. Each item is represented
# as a tuple (weight, profit).
def load(fileName):
  f = open(fileName, "r")
  lines = f.readlines()
  line = lines[0].split(",")
  nbItems = int(line[0].strip())
  maxWeight = int(line[1].strip())
  items = [None] * nbItems
  for i in range(0, nbItems):
    line = lines[i + 1].split(",")
    weight = int(line[0].strip())
    profit = float(line[1].strip())
    items[i] = (weight, profit)
  return (maxWeight, items)

problem = load("ks_4_0")
print(problem)